#ifndef TINEXUS_COMP_WINDOW_FOCUS_MANAGER_FORWARD_HPP
#define TINEXUS_COMP_WINDOW_FOCUS_MANAGER_FORWARD_HPP

#include "comp/focus/focus_manager.hpp"

#endif // TINEXUS_COMP_WINDOW_FOCUS_MANAGER_FORWARD_HPP
