/* Generated by wayland-scanner 1.24.0 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef WL_PRIVATE
#undef WL_PRIVATE
#endif
#define WL_PRIVATE

extern const struct wl_interface wl_output_interface;
extern const struct wl_interface wl_seat_interface;
extern const struct wl_interface wl_surface_interface;
extern const struct wl_interface zwlr_foreign_toplevel_manager_v1_interface;
extern const struct wl_interface zwlr_foreign_toplevel_handle_v1_interface;

static const struct wl_interface *wlr_foreign_toplevel_management_unstable_v1_types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
	&zwlr_foreign_toplevel_handle_v1_interface,
	&wl_seat_interface,
	&wl_surface_interface,
	NULL,
	NULL,
	NULL,
	NULL,
	&wl_output_interface,
	&wl_output_interface,
	&wl_output_interface,
	&zwlr_foreign_toplevel_handle_v1_interface,
};

static const struct wl_message zwlr_foreign_toplevel_manager_v1_requests[] = {
	{ "stop", "", wlr_foreign_toplevel_management_unstable_v1_types + 0 },
};

static const struct wl_message zwlr_foreign_toplevel_manager_v1_events[] = {
	{ "toplevel", "n", wlr_foreign_toplevel_management_unstable_v1_types + 4 },
	{ "finished", "", wlr_foreign_toplevel_management_unstable_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface zwlr_foreign_toplevel_manager_v1_interface = {
	"zwlr_foreign_toplevel_manager_v1", 3,
	1, zwlr_foreign_toplevel_manager_v1_requests,
	2, zwlr_foreign_toplevel_manager_v1_events,
};

static const struct wl_message zwlr_foreign_toplevel_handle_v1_requests[] = {
	{ "set_maximized", "", wlr_foreign_toplevel_management_unstable_v1_types + 0 },
	{ "unset_maximized", "", wlr_foreign_toplevel_management_unstable_v1_types + 0 },
	{ "set_minimized", "", wlr_foreign_toplevel_management_unstable_v1_types + 0 },
	{ "unset_minimized", "", wlr_foreign_toplevel_management_unstable_v1_types + 0 },
	{ "activate", "o", wlr_foreign_toplevel_management_unstable_v1_types + 5 },
	{ "close", "", wlr_foreign_toplevel_management_unstable_v1_types + 0 },
	{ "set_rectangle", "oiiii", wlr_foreign_toplevel_management_unstable_v1_types + 6 },
	{ "destroy", "", wlr_foreign_toplevel_management_unstable_v1_types + 0 },
	{ "set_fullscreen", "2?o", wlr_foreign_toplevel_management_unstable_v1_types + 11 },
	{ "unset_fullscreen", "2", wlr_foreign_toplevel_management_unstable_v1_types + 0 },
};

static const struct wl_message zwlr_foreign_toplevel_handle_v1_events[] = {
	{ "title", "s", wlr_foreign_toplevel_management_unstable_v1_types + 0 },
	{ "app_id", "s", wlr_foreign_toplevel_management_unstable_v1_types + 0 },
	{ "output_enter", "o", wlr_foreign_toplevel_management_unstable_v1_types + 12 },
	{ "output_leave", "o", wlr_foreign_toplevel_management_unstable_v1_types + 13 },
	{ "state", "a", wlr_foreign_toplevel_management_unstable_v1_types + 0 },
	{ "done", "", wlr_foreign_toplevel_management_unstable_v1_types + 0 },
	{ "closed", "", wlr_foreign_toplevel_management_unstable_v1_types + 0 },
	{ "parent", "3?o", wlr_foreign_toplevel_management_unstable_v1_types + 14 },
};

WL_PRIVATE const struct wl_interface zwlr_foreign_toplevel_handle_v1_interface = {
	"zwlr_foreign_toplevel_handle_v1", 3,
	10, zwlr_foreign_toplevel_handle_v1_requests,
	8, zwlr_foreign_toplevel_handle_v1_events,
};

#ifdef __cplusplus
}
#endif
