#!/bin/bash
# ==============================================================================
# Tinexus Platform — Calamares Automated Target Disk Installation
# Implements: partition, mount, unpackfs, fstab, bootloader, shellprocess
# ==============================================================================
set -euo pipefail

RAW_DISK="/mnt/host/d/tinexus-target.raw"
ISO_PATH="/workspace/build/Tinexus-x86_64.iso"
TARGET_MOUNT="/mnt/target"

info()    { echo -e "\e[1;34m[CALAMARES-INSTALL]\e[0m $1"; }
success() { echo -e "\e[1;32m[SUCCESS]\e[0m $1"; }
fatal()   { echo -e "\e[1;31m[FATAL]\e[0m $1"; exit 1; }

info "1. Verifying ISO and virtual raw disk..."
[ -f "$ISO_PATH" ] || fatal "ISO not found: $ISO_PATH"
[ -f "$RAW_DISK" ] || truncate -s 20G "$RAW_DISK"

info "2. Setting up loop device with partition scan..."
umount /mnt/target/boot/efi 2>/dev/null || true
umount -l /mnt/target 2>/dev/null || true
losetup -D 2>/dev/null || true
sleep 1
LOOP_DEV=$(losetup -fP --show "$RAW_DISK")
info "Attached $RAW_DISK to $LOOP_DEV"

cleanup() {
    info "Running cleanup handler..."
    umount "$TARGET_MOUNT/boot/efi" 2>/dev/null || true
    umount -l "$TARGET_MOUNT" 2>/dev/null || true
    umount /mnt/isomnt 2>/dev/null || true
    losetup -d "$LOOP_DEV" 2>/dev/null || true
}
trap cleanup EXIT

info "3. Partitioning virtual drive via sfdisk (GPT, 512MB EFI, 19.5GB ext4)..."
echo -e "label: gpt\n,512M,C12A7328-F81F-11D2-BA4B-00A0C93EC93B\n,,0FC63DAF-8483-4772-8E79-3D69D8477DE4" | sfdisk --wipe always "$LOOP_DEV"
sync
sleep 1

# Re-attach loop with partition scan
losetup -d "$LOOP_DEV" 2>/dev/null || true
LOOP_DEV=$(losetup -fP --show "$RAW_DISK")
sleep 1

ESP_PART="${LOOP_DEV}p1"
ROOT_PART="${LOOP_DEV}p2"
[ -b "$ESP_PART" ] || fatal "EFI partition $ESP_PART not found!"
[ -b "$ROOT_PART" ] || fatal "Root partition $ROOT_PART not found!"

info "4. Formatting partitions (FAT32 for ESP, ext4 for root)..."
mkfs.vfat -F32 -n "TINEXUS_ESP" "$ESP_PART"
mkfs.ext4 -F -L "TINEXUS_ROOT" "$ROOT_PART"

info "5. Mounting target file systems..."
mkdir -p "$TARGET_MOUNT"
mount "$ROOT_PART" "$TARGET_MOUNT"
mkdir -p "$TARGET_MOUNT/boot/efi"
mount "$ESP_PART" "$TARGET_MOUNT/boot/efi"

info "6. Unpacking system from live SquashFS (Calamares unpackfs)..."
mkdir -p /mnt/isomnt
if ! mount | grep -q '/mnt/isomnt'; then
    mount -o loop,ro "$ISO_PATH" /mnt/isomnt
fi

mksquash_src="/mnt/isomnt/live/rootfs.squashfs"
[ -f "$mksquash_src" ] || fatal "Squashfs not found at $mksquash_src"

unsquashfs -f -d "$TARGET_MOUNT" "$mksquash_src"
success "Extracted root filesystem to target disk."

info "7. Generating fstab (Calamares fstab module)..."
ESP_UUID=$(blkid -s UUID -o value "$ESP_PART")
ROOT_UUID=$(blkid -s UUID -o value "$ROOT_PART")

cat > "$TARGET_MOUNT/etc/fstab" << EOF_FSTAB
# /etc/fstab: static file system information generated by Calamares
UUID=$ROOT_UUID /               ext4    errors=remount-ro 0       1
UUID=$ESP_UUID  /boot/efi       vfat    umask=0077      0       1
EOF_FSTAB

info "8. Configuring UEFI bootloader (Calamares bootloader module)..."
mkdir -p "$TARGET_MOUNT/boot/efi/EFI/BOOT" "$TARGET_MOUNT/boot/efi/EFI/tinexus" "$TARGET_MOUNT/boot/grub"

if [ -f "$TARGET_MOUNT/usr/lib/shim/shimx64.efi.signed" ]; then
    cp -f "$TARGET_MOUNT/usr/lib/shim/shimx64.efi.signed" "$TARGET_MOUNT/boot/efi/EFI/BOOT/BOOTX64.EFI"
    cp -f "$TARGET_MOUNT/usr/lib/shim/shimx64.efi.signed" "$TARGET_MOUNT/boot/efi/EFI/tinexus/shimx64.efi"
elif [ -f "/mnt/isomnt/EFI/BOOT/BOOTX64.EFI" ]; then
    cp -f "/mnt/isomnt/EFI/BOOT/BOOTX64.EFI" "$TARGET_MOUNT/boot/efi/EFI/BOOT/BOOTX64.EFI"
fi

if [ -f "$TARGET_MOUNT/usr/lib/grub/x86_64-efi-signed/grubx64.efi.signed" ]; then
    cp -f "$TARGET_MOUNT/usr/lib/grub/x86_64-efi-signed/grubx64.efi.signed" "$TARGET_MOUNT/boot/efi/EFI/BOOT/grubx64.efi"
    cp -f "$TARGET_MOUNT/usr/lib/grub/x86_64-efi-signed/grubx64.efi.signed" "$TARGET_MOUNT/boot/efi/EFI/tinexus/grubx64.efi"
elif [ -f "/mnt/isomnt/EFI/BOOT/grubx64.efi" ]; then
    cp -f "/mnt/isomnt/EFI/BOOT/grubx64.efi" "$TARGET_MOUNT/boot/efi/EFI/BOOT/grubx64.efi"
fi

# Detect installed kernel and initrd in target
VMLINUZ_INSTALLED=$(ls -1 "$TARGET_MOUNT/boot"/vmlinuz* 2>/dev/null | head -1 | xargs -n1 basename || echo "vmlinuz")
INITRD_INSTALLED=$(ls -1 "$TARGET_MOUNT/boot"/initrd* 2>/dev/null | head -1 | xargs -n1 basename || echo "initrd.img")

cat > "$TARGET_MOUNT/boot/grub/grub.cfg" << EOF_GRUB
set default=0
set timeout=2

menuentry "Tinexus OS" {
    search --no-floppy --fs-uuid --set=root $ROOT_UUID
    linux /boot/$VMLINUZ_INSTALLED root=UUID=$ROOT_UUID rw quiet splash console=ttyS0,115200n8 console=tty0
    initrd /boot/$INITRD_INSTALLED
}
EOF_GRUB

cp -f "$TARGET_MOUNT/boot/grub/grub.cfg" "$TARGET_MOUNT/boot/efi/EFI/BOOT/grub.cfg"
cp -f "$TARGET_MOUNT/boot/grub/grub.cfg" "$TARGET_MOUNT/boot/efi/EFI/tinexus/grub.cfg"

info "9. Executing postinstall hooks (Calamares shellprocess module)..."
# Setup machine-id
if command -v systemd-machine-id-setup >/dev/null 2>&1; then
    systemd-machine-id-setup --root="$TARGET_MOUNT" 2>/dev/null || true
else
    cat /proc/sys/kernel/random/boot_id | tr -d '-' > "$TARGET_MOUNT/etc/machine-id" 2>/dev/null || true
fi

# Enable systemd graphical session
mkdir -p "$TARGET_MOUNT/etc/systemd/system/default.target.wants"
ln -sf /lib/systemd/system/graphical.target "$TARGET_MOUNT/etc/systemd/system/default.target" 2>/dev/null || true

success "=================================================================="
success "Calamares Installation to $RAW_DISK completed successfully!"
success "Partitions: $ESP_PART (EFI), $ROOT_PART (Root)"
success "Root UUID:  $ROOT_UUID"
success "EFI UUID:   $ESP_UUID"
success "Kernel:     $VMLINUZ_INSTALLED"
success "=================================================================="
