#include "common/GraphicsProbe.hpp"
#include "common/logger.hpp"
#include <iostream>
#include <fstream>
#include <filesystem>

int main(int argc, char** argv) {
    namespace fs = std::filesystem;
    tinexus::log::info("[probe] tinexus-hardware-probe: Evaluating GPU capabilities...");

    try {
        fs::create_directories("/run/tinexus");
    } catch (const std::exception& ex) {
        std::cerr << "Failed to create /run/tinexus: " << ex.what() << std::endl;
    }

    auto probe_result = tinexus::hardware::GraphicsProbe::evaluate();

    std::ofstream out("/run/tinexus/env");
    if (!out.is_open()) {
        tinexus::log::error("[probe] Failed to open /run/tinexus/env for writing");
        return 1;
    }

    out << "# Auto-generated by tinexus-hardware-probe\n";
    out << "LIBSEAT_BACKEND=seatd\n";
    out << "WLR_DRM_NO_ATOMIC=1\n";
    out << "WLR_NO_HARDWARE_CURSORS=1\n";

    if (probe_result.hardware_available) {
        out << "WLR_RENDERER=gles2\n";
        if (!probe_result.selected_card_node.empty()) {
            out << "WLR_DRM_DEVICES=" << probe_result.selected_card_node << "\n";
            tinexus::log::info("[probe] Bound primary DRM KMS card: {}", probe_result.selected_card_node);
        }
        tinexus::log::info("[probe] Hardware GLES2 acceleration confirmed (EGL {})", probe_result.egl_version);
    } else {
        tinexus::log::warn("[probe] Hardware pre-flight probe did not lock hardware: {}", probe_result.reason);
        tinexus::log::info("[probe] Leaving WLR_RENDERER unset for native wlroots compositor auto-detection");
    }
    out.flush();

    tinexus::log::info("[probe] Hardware environment successfully written to /run/tinexus/env");
    return 0;
}
