#include "common/HardwareConfig.hpp"
#include <algorithm>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <cstdlib>
#include <unistd.h>
#include <fcntl.h>
#include <sys/stat.h>

namespace fs = std::filesystem;

namespace tinexus::hardware {

std::string HardwareConfig::default_config_path() {
    const char* home = std::getenv("HOME");
    if (home && fs::exists(home)) {
        return (fs::path(home) / ".config" / "tinexus" / "hardware.toml").string();
    }
    if (fs::exists("/home/tinexus/.config")) {
        return "/home/tinexus/.config/tinexus/hardware.toml";
    }
    return "/etc/tinexus/hardware.toml";
}

HardwareSettings HardwareConfig::load(const std::string& custom_path) {
    HardwareSettings settings{};
    std::string path = custom_path.empty() ? default_config_path() : custom_path;

    if (!fs::exists(path)) {
        // Fallback to system-level config if user-level doesn't exist
        if (custom_path.empty() && fs::exists("/etc/tinexus/hardware.toml")) {
            path = "/etc/tinexus/hardware.toml";
        } else {
            return settings;
        }
    }

    std::ifstream file(path);
    if (!file.is_open()) return settings;

    std::string line;
    std::string current_section;
    while (std::getline(file, line)) {
        // Trim whitespace
        auto start = line.find_first_not_of(" \t\r\n");
        if (start == std::string::npos) continue;
        auto end = line.find_last_not_of(" \t\r\n");
        line = line.substr(start, end - start + 1);

        if (line.empty() || line[0] == '#') continue;

        if (line.front() == '[' && line.back() == ']') {
            current_section = line.substr(1, line.length() - 2);
            continue;
        }

        auto eq_pos = line.find('=');
        if (eq_pos == std::string::npos) continue;

        std::string key = line.substr(0, eq_pos);
        std::string val = line.substr(eq_pos + 1);

        auto trim_str = [](std::string& s) {
            auto s_idx = s.find_first_not_of(" \t\r\n\"");
            auto e_idx = s.find_last_not_of(" \t\r\n\"");
            if (s_idx != std::string::npos && e_idx != std::string::npos) {
                s = s.substr(s_idx, e_idx - s_idx + 1);
            }
        };
        trim_str(key);
        trim_str(val);

        if (current_section == "audio") {
            if (key == "volume") {
                try {
                    int v = std::stoi(val);
                    settings.volume = std::clamp(v, 0, 100);
                } catch (...) {}
            } else if (key == "muted") {
                settings.muted = (val == "true" || val == "1");
            }
        } else if (current_section == "display") {
            if (key == "brightness") {
                try {
                    int b = std::stoi(val);
                    settings.brightness = std::clamp(b, 5, 100);
                } catch (...) {}
            }
        }
    }

    return settings;
}

bool HardwareConfig::save(const HardwareSettings& settings, const std::string& custom_path) {
    std::string target_path = custom_path.empty() ? default_config_path() : custom_path;

    try {
        fs::path p(target_path);
        if (p.has_parent_path() && !fs::exists(p.parent_path())) {
            std::error_code ec;
            fs::create_directories(p.parent_path(), ec);
        }

        std::string tmp_path = target_path + ".tmp";
        {
            std::ofstream out(tmp_path, std::ios::trunc);
            if (!out.is_open()) return false;

            out << "# Tinexus Platform Hardware Configuration\n";
            out << "# Automatically generated by Tinexus Desktop Shell\n\n";
            out << "[audio]\n";
            out << "volume = " << std::clamp(settings.volume, 0, 100) << "\n";
            out << "muted = " << (settings.muted ? "true" : "false") << "\n\n";
            out << "[display]\n";
            out << "brightness = " << std::clamp(settings.brightness, 5, 100) << "\n";
            out.flush();
        }

        // Fsync to ensure physical media durability before rename
        int fd = ::open(tmp_path.c_str(), O_RDONLY);
        if (fd >= 0) {
            ::fsync(fd);
            ::close(fd);
        }

        // Atomic replace
        std::error_code ec;
        fs::rename(tmp_path, target_path, ec);
        if (ec) {
            fs::remove(tmp_path, ec);
            return false;
        }

        // Ensure permissive ownership for tinexus user if written as root
        struct stat st;
        if (::stat(target_path.c_str(), &st) == 0 && st.st_uid == 0 && fs::exists("/home/tinexus")) {
            if (::chown(target_path.c_str(), 1000, 1000) != 0) {
                // Non-critical, ignore
            }
        }

        return true;
    } catch (...) {
        return false;
    }
}

} // namespace tinexus::hardware
